### ISSUE TITLE
Can't build libmxnet_predict.js with latest mxnet

### ISSUE THREAD

**Issue by semyonc** [dmlc/mxnet.js#18]
Running 
make clean libmxnet_predict.js MIN=1 EMCC="docker run -v ${PWD}:/src apiaryio/emcc emcc"
ends with errors:

docker run -v /Users/semyonc/Projects/mxnet.js/mxnet/amalgamation:/src apiaryio/emcc emcc -std=c++11 -O2 --memory-init-file 0 -DMSHADOW_USE_CBLAS=0 -DDISABLE_OPENMP=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DDMLC_LOG_STACK_TRACE=0 -DMSHADOW_FORCE_STREAM -DMXNET_USE_OPENCV=0 -DMXNET_PREDICT_ONLY=1 -DMSHADOW_USE_SSE=0 -D__MXNET_JS__  -o libmxnet_predict.js mxnet_predict-all.cc \
	-s EXPORTED_FUNCTIONS="['_MXPredCreate', \
	                        '_MXPredGetOutputShape', \
	                        '_MXPredSetInput', \
	                        '_MXPredForward', \
	                        '_MXPredPartialForward', \
	                        '_MXPredGetOutput', \
	                        '_MXPredFree', \
	                        '_MXNDListCreate', \
	                        '_MXNDListGet', \
	                        '_MXNDListFree']" \
	-s ALLOW_MEMORY_GROWTH=1
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those. [-Walmost-asm]
mxnet_predict-all.cc:8706:9: warning: 'MSHADOW_FORCE_STREAM' macro redefined [-Wmacro-redefined]
#define MSHADOW_FORCE_STREAM
        ^
<command line>:12:9: note: previous definition is here
#define MSHADOW_FORCE_STREAM 1
        ^
mxnet_predict-all.cc:19388:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MSHADOW_IN_CXX11
    ^
mxnet_predict-all.cc:8844:27: note: expanded from macro 'MSHADOW_IN_CXX11'
#define MSHADOW_IN_CXX11 (defined(__GXX_EXPERIMENTAL_CXX0X__) ||\
                          ^
mxnet_predict-all.cc:19388:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
mxnet_predict-all.cc:8845:53: note: expanded from macro 'MSHADOW_IN_CXX11'
                          __cplusplus >= 201103L || defined(_MSC_VER))
                                                    ^
mxnet_predict-all.cc:19986:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MSHADOW_IN_CXX11
    ^
mxnet_predict-all.cc:8844:27: note: expanded from macro 'MSHADOW_IN_CXX11'
#define MSHADOW_IN_CXX11 (defined(__GXX_EXPERIMENTAL_CXX0X__) ||\
                          ^
mxnet_predict-all.cc:19986:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
mxnet_predict-all.cc:8845:53: note: expanded from macro 'MSHADOW_IN_CXX11'
                          __cplusplus >= 201103L || defined(_MSC_VER))
                                                    ^
mxnet_predict-all.cc:20022:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MSHADOW_IN_CXX11
    ^
mxnet_predict-all.cc:8844:27: note: expanded from macro 'MSHADOW_IN_CXX11'
#define MSHADOW_IN_CXX11 (defined(__GXX_EXPERIMENTAL_CXX0X__) ||\
                          ^
mxnet_predict-all.cc:20022:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
mxnet_predict-all.cc:8845:53: note: expanded from macro 'MSHADOW_IN_CXX11'
                          __cplusplus >= 201103L || defined(_MSC_VER))
                                                    ^
mxnet_predict-all.cc:20042:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MSHADOW_IN_CXX11
    ^
mxnet_predict-all.cc:8844:27: note: expanded from macro 'MSHADOW_IN_CXX11'
#define MSHADOW_IN_CXX11 (defined(__GXX_EXPERIMENTAL_CXX0X__) ||\
                          ^
mxnet_predict-all.cc:20042:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
mxnet_predict-all.cc:8845:53: note: expanded from macro 'MSHADOW_IN_CXX11'
                          __cplusplus >= 201103L || defined(_MSC_VER))
                                                    ^
mxnet_predict-all.cc:20229:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MSHADOW_IN_CXX11
    ^
mxnet_predict-all.cc:8844:27: note: expanded from macro 'MSHADOW_IN_CXX11'
#define MSHADOW_IN_CXX11 (defined(__GXX_EXPERIMENTAL_CXX0X__) ||\
                          ^
mxnet_predict-all.cc:20229:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
mxnet_predict-all.cc:8845:53: note: expanded from macro 'MSHADOW_IN_CXX11'
                          __cplusplus >= 201103L || defined(_MSC_VER))
                                                    ^
mxnet_predict-all.cc:35697:9: warning: 'API_END' macro redefined [-Wmacro-redefined]
#define API_END() } catch(dmlc::Error &_except_) { return MXAPIHandleException(_except_); } return 0;  // NOLINT(*)
        ^
mxnet_predict-all.cc:27288:9: note: previous definition is here
#define API_END() } catch(dmlc::Error &_except_) { return NNAPIHandleException(_except_); } return 0;  // NOLINT(*)
        ^
mxnet_predict-all.cc:35703:9: warning: 'API_END_HANDLE_ERROR' macro redefined [-Wmacro-redefined]
#define API_END_HANDLE_ERROR(Finalize) } catch(dmlc::Error &_except_) { Finalize; return MXAPIHandleException(_except_); } return 0; // NOLINT(*)
        ^
mxnet_predict-all.cc:27294:9: note: previous definition is here
#define API_END_HANDLE_ERROR(Finalize) } catch(dmlc::Error &_except_) { Finalize; return NNAPIHandleException(_except_); } return 0; // NOLINT(*)
        ^
mxnet_predict-all.cc:42493:53: error: no member named 'RangeOutSize' in namespace 'mshadow::expr'
                     mshadow::Shape1(mshadow::expr::RangeOutSize(param.start,
                                     ~~~~~~~~~~~~~~~^
mxnet_predict-all.cc:37428:53: note: expanded from macro 'SHAPE_ASSIGN_CHECK'
    if (!shape_assign(&(shape_array)[index], TShape(shape))) {              \
                                                    ^~~~~
mxnet_predict-all.cc:42493:53: error: no member named 'RangeOutSize' in namespace 'mshadow::expr'
                     mshadow::Shape1(mshadow::expr::RangeOutSize(param.start,
                                     ~~~~~~~~~~~~~~~^
mxnet_predict-all.cc:37431:35: note: expanded from macro 'SHAPE_ASSIGN_CHECK'
         << " inferred shape=" << shape;                                    \
                                  ^~~~~
mxnet_predict-all.cc:50941:11: warning: Warning: lapack usage not enabled, linalg-operators will not be available. Ensure that lapack library is installed and build with USE_LAPACK=1 to get lapack functionalities. [-W#pragma-messages]
  #pragma message("Warning: lapack usage not enabled, linalg-operators will not be available." \
          ^
mxnet_predict-all.cc:52179:29: error: invalid operands to binary expression ('const dmlc::optional<int>' and 'const dmlc::optional<int>')
           this->cudnn_tune == other.cudnn_tune &&
           ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
mxnet_predict-all.cc:52181:25: error: invalid operands to binary expression ('const dmlc::optional<int>' and 'const dmlc::optional<int>')
           this->layout == other.layout;
           ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
mxnet_predict-all.cc:52193:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.kernel);
          ~~~~~~^
mxnet_predict-all.cc:52194:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.stride);
          ~~~~~~^
mxnet_predict-all.cc:52195:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.dilate);
          ~~~~~~^
mxnet_predict-all.cc:52196:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.pad);
          ~~~~~~^
mxnet_predict-all.cc:52197:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.num_filter);
          ~~~~~~^
mxnet_predict-all.cc:52198:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.num_group);
          ~~~~~~^
mxnet_predict-all.cc:52199:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.workspace);
          ~~~~~~^
mxnet_predict-all.cc:52200:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.no_bias);
          ~~~~~~^
mxnet_predict-all.cc:52201:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.cudnn_tune);
          ~~~~~~^
mxnet_predict-all.cc:52202:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.cudnn_off);
          ~~~~~~^
mxnet_predict-all.cc:52203:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.layout);
          ~~~~~~^
mxnet_predict-all.cc:53074:29: error: invalid operands to binary expression ('const dmlc::optional<int>' and 'const dmlc::optional<int>')
           this->cudnn_tune == other.cudnn_tune &&
           ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
mxnet_predict-all.cc:53076:25: error: invalid operands to binary expression ('const dmlc::optional<int>' and 'const dmlc::optional<int>')
           this->layout == other.layout;
           ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
mxnet_predict-all.cc:53088:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.kernel);
          ~~~~~~^
mxnet_predict-all.cc:53089:17: error: no member named 'HashCombine' in namespace 'dmlc'
    ret = dmlc::HashCombine(ret, val.stride);
          ~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [libmxnet_predict.js] Error 1

**Comment by Soonhwan-Kwon** [comment]
I successfully build on latest mxnet, but I installed Emscripten and used command "make clean libmxnet_predict.js MIN=1".

**Comment by semyonc** [comment]
Yes, it turned out. I successfully build on latest mxnet with clear copy of source tree
